import * as T from './vendor/three.module.js';
import {Chess} from './vendor/chess.mjs';
const $=s=>document.querySelector(s),game=new Chess();let mode='computer',selected=null,pending=null,thinking=false,epoch=0,worker=null,renderer;
const container=$('#board'),scene=new T.Scene(),camera=new T.OrthographicCamera(-4.6,4.6,4.6,-4.6,.1,100);camera.position.set(0,16,9);camera.lookAt(0,.28,0);
try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('#loading').textContent='3D-grafiken kunde inte starta. Prova Safari eller Chrome med WebGL aktiverat.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;container.appendChild(renderer.domElement);
const envScene=new T.Scene();envScene.background=new T.Color('#29415c');const panelMat=new T.MeshBasicMaterial({color:'#ffffff'});
for(const [x,y,z,w,h] of [[-4,6,2,3,7],[5,4,-3,2,5],[0,7,0,7,2]]){const panel=new T.Mesh(new T.PlaneGeometry(w,h),panelMat);panel.position.set(x,y,z);panel.lookAt(0,0,0);envScene.add(panel);}
const pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(envScene,.03);scene.environment=environment.texture;
scene.add(new T.HemisphereLight(0xd9efff,0x122139,2));const light=new T.DirectionalLight(0xf3faff,3);light.position.set(-3,9,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-6,right:6,top:6,bottom:-6});light.shadow.bias=-.001;scene.add(light);const rim=new T.DirectionalLight(0x579eea,2);rim.position.set(5,5,-5);scene.add(rim);
const frame=new T.Mesh(new T.BoxGeometry(8.45,.2,8.45),new T.MeshStandardMaterial({color:0x1a2b40,metalness:.7,roughness:.25}));frame.position.y=-.18;frame.receiveShadow=true;scene.add(frame);
const squares=[],pieces=new T.Group(),markers=new T.Group();scene.add(pieces,markers);
for(let row=0;row<8;row++)for(let col=0;col<8;col++){const sq=String.fromCharCode(97+col)+(8-row),tile=new T.Mesh(new T.BoxGeometry(.996,.10,.996),new T.MeshStandardMaterial({color:(row+col)%2===0?0x66819d:0x172737,roughness:.6,metalness:.15}));tile.position.set(col-3.5,-.03,row-3.5);tile.receiveShadow=true;tile.userData.square=sq;scene.add(tile);squares.push(tile);}
const white=new T.MeshPhysicalMaterial({color:0xe6f8ff,metalness:0,roughness:.08,transmission:.94,thickness:.55,ior:1.45,transparent:true,opacity:1,envMapIntensity:1.7,clearcoat:1,attenuationColor:new T.Color(0xbde5ff),attenuationDistance:5});const black=white.clone();black.color.set(0x5786b1);black.attenuationColor.set(0x22436a);black.attenuationDistance=1.4;black.transmission=.87;
// Frosted white glass keeps a readable silhouette on both square colors.
white.color.set(0xd9e6ef);white.roughness=.38;white.transmission=.40;white.envMapIntensity=.72;white.clearcoat=.25;white.clearcoatRoughness=.4;white.attenuationDistance=2;
const eyeMaterial=new T.MeshStandardMaterial({color:0x203c55,roughness:.55,metalness:.15});
const geometries={};
function lathe(points){return new T.LatheGeometry(points.map(([r,y])=>new T.Vector2(r,y)),40);}
const base=lathe([[0,0],[.27,0],[.32,.045],[.32,.09],[.27,.14],[.24,.17],[.27,.20],[.24,.23],[0,.23]]);
function buildPiece(type){const parts=[{g:base}];const stem=lathe([[0,.19],[.22,.19],[.22,.25],[.17,.30],[.13,.40],[.11,.55],[.15,.61],[.22,.63],[.22,.68],[.13,.70],[0,.70]]);if(type==='p'){parts.push({g:lathe([[0,.18],[.20,.18],[.18,.25],[.12,.36],[.10,.47],[.16,.50],[.16,.55],[0,.55]])},{g:new T.SphereGeometry(.16,24,16),p:[0,.68,0]});}
else if(type==='r'){parts.push({g:lathe([[0,.2],[.21,.2],[.20,.3],[.17,.68],[.23,.70],[.25,.76],[.25,.84],[0,.84]])});for(let i=0;i<6;i++){const a=i*Math.PI/3;parts.push({g:new T.BoxGeometry(.13,.15,.13),p:[Math.sin(a)*.20,.88,Math.cos(a)*.20],r:[0,a,0]});}}
else if(type==='n'){
 parts.push({g:new T.CylinderGeometry(.16,.23,.18,32),p:[0,.30,0]});
 const s=new T.Shape();s.moveTo(-.22,.36);
 s.bezierCurveTo(-.23,.53,-.26,.74,-.19,.90);
 s.quadraticCurveTo(-.13,1.03,-.04,1.07);
 s.lineTo(-.04,1.20);s.lineTo(.04,1.16);s.lineTo(.075,1.07);
 s.quadraticCurveTo(.15,1.01,.18,.96);
 s.lineTo(.36,.86);s.quadraticCurveTo(.40,.81,.34,.76);
 s.lineTo(.22,.76);s.lineTo(.09,.85);
 s.quadraticCurveTo(.015,.70,.075,.60);
 s.quadraticCurveTo(.16,.47,.23,.36);s.closePath();
 const g=new T.ExtrudeGeometry(s,{depth:.24,bevelEnabled:true,bevelSegments:4,steps:1,bevelSize:.035,bevelThickness:.035,curveSegments:18});g.translate(0,0,-.12);
 // Broad side faces the player; the old 90-degree turn hid the horse profile.
 parts.push({g});
 for(const z of [-.154,.154])parts.push({g:new T.SphereGeometry(.026,16,12),p:[.08,.985,z],mat:eyeMaterial});
}
else{parts.push({g:stem});if(type==='b'){parts.push({g:lathe([[0,.67],[.14,.70],[.20,.78],[.19,.85],[.14,.95],[.04,1.07],[0,1.09]])},{g:new T.SphereGeometry(.05,16,12),p:[0,1.13,0]});}if(type==='q'){parts.push({g:lathe([[0,.69],[.14,.70],[.20,.85],[.26,.99],[.23,1.03],[.10,1.01],[.08,.91],[0,.9]])});for(let i=0;i<7;i++){const a=i*Math.PI*2/7;parts.push({g:new T.SphereGeometry(.045,16,12),p:[Math.sin(a)*.235,1.06,Math.cos(a)*.235]});}parts.push({g:new T.SphereGeometry(.065,16,12),p:[0,1.06,0]});}if(type==='k'){parts.push({g:lathe([[0,.67],[.14,.69],[.21,.74],[.22,.84],[.16,.94],[.11,.97],[0,.97]])},{g:new T.BoxGeometry(.07,.27,.075),p:[0,1.08,0]},{g:new T.BoxGeometry(.23,.065,.075),p:[0,1.10,0]});}}
return parts;}
for(const t of ['p','r','n','b','q','k'])geometries[t]=buildPiece(t);
function position(square){return new T.Vector3(square.charCodeAt(0)-97-3.5,.045,8-Number(square[1])-3.5);}
function disposeMarkers(){for(const c of [...markers.children]){c.geometry.dispose();c.material.dispose();markers.remove(c);}}
function drawMarkers(){disposeMarkers();if(!selected)return;const legal=game.moves({square:selected,verbose:true});for(const sq of [selected,...legal.map(x=>x.to)]){const chosen=sq===selected,capture=!!game.get(sq),g=chosen||capture?new T.RingGeometry(.34,.43,40):new T.CircleGeometry(.115,24),m=new T.MeshBasicMaterial({color:chosen?0x5dd7ff:0x65efa5,transparent:true,opacity:.85,side:T.DoubleSide}),mesh=new T.Mesh(g,m);mesh.rotation.x=-Math.PI/2;mesh.position.copy(position(sq));mesh.position.y=.035;markers.add(mesh);}}
function drawPieces(){pieces.clear();for(const row of game.board())for(const p of row){if(!p)continue;const group=new T.Group();for(const part of geometries[p.type]){const mesh=new T.Mesh(part.g,part.mat||(p.color==='w'?white:black));if(part.p)mesh.position.set(...part.p);if(part.r)mesh.rotation.set(...part.r);mesh.castShadow=true;mesh.userData.square=p.square;group.add(mesh);}group.position.copy(position(p.square));if(p.color==='b')group.rotation.y=Math.PI;pieces.add(group);}}
function describeStatus(){if(game.isCheckmate())return(game.turn()==='w'?'Svart':'Vit')+' vinner · schackmatt';if(game.isStalemate())return'Remi · patt';if(game.isThreefoldRepetition())return'Remi · upprepning';if(game.isInsufficientMaterial())return'Remi · otillräckligt material';if(game.isDraw())return'Remi';if(thinking)return'Datorn tänker…';return(game.turn()==='w'?'Vits tur':'Svarts tur')+(game.isCheck()?' · schack':'');}
function sync(){drawPieces();drawMarkers();$('#status').textContent=describeStatus();$('#hint').textContent=game.isGameOver()?'Starta ett nytt parti för att spela igen.':selected?'Välj en grönmarkerad ruta.':'Tryck på en pjäs för att se dina drag.';$('#undo').disabled=game.history().length===0;$('#history').innerHTML=game.history().map((x,i)=>`<li value="${Math.floor(i/2)+1}">${x}</li>`).join('');$('#accessibleBoard').innerHTML=squares.map(s=>{const p=game.get(s.userData.square);return`<button data-square="${s.userData.square}" aria-label="${s.userData.square} ${p?(p.color==='w'?'vit':'svart')+' '+({p:'bonde',n:'springare',b:'löpare',r:'torn',q:'dam',k:'kung'}[p.type]):'tom ruta'}">${s.userData.square}</button>`;}).join('');}
function invalidate(){epoch++;thinking=false;worker?.terminate();worker=null;selected=null;pending=null;if($('#promotion').open)$('#promotion').close();}
function scheduleAI(){if(mode!=='computer'||game.turn()!=='b'||game.isGameOver())return;thinking=true;sync();const id=++epoch;try{worker=new Worker(new URL('./ai.mjs',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.id!==epoch)return;worker.terminate();worker=null;thinking=false;if(e.data.move)game.move(e.data.move);selected=null;sync();};worker.onerror=()=>{if(id!==epoch)return;worker?.terminate();worker=null;thinking=false;$('#status').textContent='Datorn kunde inte starta. Välj två spelare eller nytt parti.';};worker.postMessage({id,fen:game.fen(),level:Number($('#difficulty').value)});}catch{thinking=false;$('#status').textContent='Datorn kunde inte starta. Välj två spelare.';}}
function move(from,to,promotion){try{game.move({from,to,promotion});selected=null;sync();scheduleAI();return true;}catch{return false;}}
function selectSquare(sq){if(thinking||game.isGameOver()||pending)return;if(mode==='computer'&&game.turn()!=='w')return;if(selected){const choices=game.moves({square:selected,verbose:true}).filter(m=>m.to===sq);if(choices.length){if(choices.some(x=>x.promotion)){pending={from:selected,to:sq};$('#promotion').showModal();}else move(selected,sq);return;}}const p=game.get(sq);selected=p&&p.color===game.turn()&&sq!==selected?sq:null;drawMarkers();$('#hint').textContent=selected?'Välj en grönmarkerad ruta.':'Tryck på en pjäs för att se dina drag.';}
const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>15){down=null;return;}down=null;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...pieces.children,...squares],true);const hit=hits.find(x=>x.object.userData.square);if(hit)selectSquare(hit.object.userData.square);});
$('#accessibleBoard').onclick=e=>{const b=e.target.closest('[data-square]');if(b)selectSquare(b.dataset.square);};
document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{if(!pending)return;const {from,to}=pending;pending=null;$('#promotion').close();move(from,to,b.dataset.p);});$('#promotion').addEventListener('cancel',()=>{pending=null;});
function reset(){invalidate();game.reset();sync();}
$('#new').onclick=()=>{if(game.history().length&&!confirm('Börja ett nytt parti?'))return;reset();};$('#undo').onclick=()=>{invalidate();if(mode==='computer'&&game.turn()==='w'&&game.history().length>=2){game.undo();game.undo();}else game.undo();sync();};
function setMode(next){if(mode===next)return;if(game.history().length&&!confirm('Byta spelläge och börja ett nytt parti?'))return;mode=next;$('#computer').setAttribute('aria-pressed',String(mode==='computer'));$('#local').setAttribute('aria-pressed',String(mode==='local'));$('#opponent').textContent=mode==='computer'?'Dator':'Spelare 2';$('#playerName').textContent=mode==='computer'?'Du':'Spelare 1';$('#difficulty').disabled=mode!=='computer';reset();}
$('#computer').onclick=()=>setMode('computer');$('#local').onclick=()=>setMode('local');$('#difficulty').onchange=()=>{if(thinking){invalidate();scheduleAI();}};
function resize(){const rect=container.getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);const aspect=rect.width/rect.height,halfHeight=Math.max(4.45,4.6/aspect);camera.left=-halfHeight*aspect;camera.right=halfHeight*aspect;camera.top=halfHeight;camera.bottom=-halfHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);resize();sync();$('#playerName').nextElementSibling.textContent='Frostat glas · vit';$('#loading').remove();
renderer.setAnimationLoop(()=>renderer.render(scene,camera));document.addEventListener('visibilitychange',()=>renderer.setAnimationLoop(document.hidden?null:()=>renderer.render(scene,camera)));
// Shared read-only state is also useful to keyboard and automated clients.
window.hqChess={getState:()=>({fen:game.fen(),turn:game.turn(),mode,thinking,history:game.history()}),selectSquare};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_chess_position',description:'Read the current HQ chess position, turn and move history.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.hqChess.getState()})).catch(()=>{});}catch{}}
